spring:
  application:
    name: T1
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: "${EMAIL_HOST}"
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

t1:
  mail:
    receiver: "${EMAIL_RECEIVER}"
  kafka:
    topic:
      mail-service: "${KAFKA_MAIL_TOPIC}"
    group: 1
    bootstrap:
      server: "${KAFKA_BOOTSTRAP_SERVER}"
    session:
      timeout:
        ms: 15000
    max:
      partition:
        fetch:
          bytes:
            300000
      poll:
        records: 1
        interval:
          ms: 3000
    consumer:
      group-id: "${KAFKA_GROUP_ID}"
